### ISSUE TITLE
Get "https://v2/": http: no host in request URL.

### ISSUE THREAD

**Issue by anmca** [Snowflake-Labs/llm-bootcamp-build-2023#15]
Getting above error while pushing the container..

**Comment by marts-dev** [comment]
Also getting the same error when pushing the docker image:

Get "https:/v2/": http: no Host in request URL

Using Docker for Windows

**Comment by vinay235** [comment]
Getting the same error. 
```
The push refers to repository [sfsenorthamerica-build_spcs2.registry.snowflakecomputing.com/db_user0010/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL
```

**Comment by anmca** [comment]
never mind. After loosing track of multiple changes finally got it to work. After image creation. I removed the tag with '_' version and rerun tag with '-' and login  and somehow need to recreate tag after login..but it did work.

**Comment by vinay235** [comment]
> never mind. After loosing track of multiple changes finally got it to work. After image creation. I removed the tag with '_' version and rerun tag with '-' and login and somehow need to recreate tag after login..but it did work. I'm referring to this underscore '_' in sfsenorthamerica-build_spcs2.

can you pls share the commands that you ran to make it work?

**Comment by vinay235** [comment]
These are the commands that worked for me, maybe someone can add this to the readme? @anmca @iamontheinet 

Example commands with ***spcs2*** version:

1.  Note that the version is seperated by '-' instead of '_' as in the account identifier

` docker tag llm-bootcamp:latest sfsenorthamerica-build-spcs2.registry.snowflakecomputing.com/db_user0010/schema_llm/image_repo/llm-bootcamp:latest `

2.  Login

`docker login sfsenorthamerica-build-spcs2.registry.snowflakecomputing.com`

3. Push image
`docker push sfsenorthamerica-build-spcs2.registry.snowflakecomputing.com/db_user0010/schema_llm/image_repo/llm-bootcamp:latest`

**Comment by mpujji** [comment]
Thank you Vinay235 - that worked
